AWSTemplateFormatVersion: '2010-09-09'
Description: >
  Sub-stack for database: DynamoDB.

Parameters:
  DynamoDBTableName:
    Type: String
    Default: visitor-counter

Resources:

  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref DynamoDBTableName
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
      KeySchema:
        - AttributeName: pk
          KeyType: HASH

Outputs:
  DynamoDBTableArn:
      Value: !GetAtt DynamoDBTable.Arn
