AWSTemplateFormatVersion: '2010-09-09'
Description: >
  Sub-stack for networking: Cloudfront, ACM, Route53.

Parameters:
  DomainName:
    Type: String
  HostedZoneId:
    Type: String
  ACMCertificateArn:
    Type: String
  SiteBucketDomain:
    Type: String
  OriginAccessControlID:
    Type: String

Resources:

  Distribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        DefaultRootObject: index.html
        Aliases: [ !Ref DomainName ]
        Origins:
          - Id: s3origin
            DomainName: !Ref SiteBucketDomain
            S3OriginConfig: {}
            OriginAccessControlId: !Ref OriginAccessControlID
        DefaultCacheBehavior:
          TargetOriginId: s3origin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods: [ GET, HEAD, OPTIONS ]
          CachedMethods: [ GET, HEAD ]
          CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6
          Compress: true
        ViewerCertificate:
          AcmCertificateArn: !Ref ACMCertificateArn
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1.2_2021
        HttpVersion: http2
        PriceClass: PriceClass_100
        CustomErrorResponses:
            - ErrorCode: 403
              ResponsePagePath: /error.html
              ResponseCode: 403
              ErrorCachingMinTTL: 10
            - ErrorCode: 404
              ResponsePagePath: /error.html
              ResponseCode: 404
              ErrorCachingMinTTL: 10

  ARecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Ref DomainName
      Type: A
      AliasTarget:
        HostedZoneId: Z2FDTNDATAQYW2
        DNSName: !GetAtt Distribution.DomainName

Outputs:
  CloudFrontDistId:
    Description: "CloudFront Distribution ID for the site"
    Value: !Ref Distribution
