name: Deploy static site

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Sync to S3
      run: aws s3 sync ./site s3://${{ env.DOMAIN }} --delete
      env:
        DOMAIN: "staging.eivistamos.co.uk"

    - name: Invalidate CloudFront cache
      run: aws cloudfront create-invalidation --distribution-id $CFID --paths "/*"
      env:
        CFID: "E10C4UIGFRF8KZ"
