name: Deploy Cloud Resume Challenge

on:
  push:
    branches: [ "main" ]

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install cfn-lint
        run: pip install cfn-lint

      - name: Run CloudFormation lint
        run: cfn-lint infra/*.yaml

      - name: Validate CloudFormation template
        run: aws cloudformation validate-template --template-body infra/main.yaml


  deploy:
    runs-on: ubuntu-latest
    needs: lint
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Configure AWS
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Upload CloudFormation templates
      run: |
        aws s3 cp infra/ s3://${{ secrets.TEMPLATE_BUCKET }}/infra/ --recursive

    - name: Deploy infrastructure
      run: |
        aws cloudformation deploy \
          --template-file infra/main.yaml \
          --stack-name resume-challenge-website \
          --capabilities CAPABILITY_NAMED_IAM

    - name: Sync frontend files
      run: |
        aws s3 sync site/ s3://${{ secrets.FRONTEND_BUCKET }}/ \
          --delete \
          --exact-timestamps
